name: Java Ci with Maven

on:
  push:
    branches: ["feature/*", "develop"]
  pull_request:
    branches: ["main", "develop"]
  schedule:
    - cron: "30 11 * * 3,5"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests with Maven
        id: test
        working-directory: todo-api
        run: mvn test
        continue-on-error: true

      - name: Build with Maven
        if: steps.test.outcome == 'success'
        working-directory: todo-api
        run: mvn -B package -DskipTests

      - name: Package application into JAR
        id: package
        if: steps.test.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: todo-api-jar
          path: todo-api/target/*.jar

      - name: Build Docker image of application
        working-directory: todo-api
        run: docker build -t my-app:test .

      - name: Publish test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-reports
          path: todo-api/target/surefire-reports

      - name: Publish test coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: todo-api/target/site/jacoco